version: '3.7'
services:
  db: 
    container_name: db_inversify
    restart: always
    image: mysql
    expose:
      - 3306
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: 'java_med'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - myapp:/var/lib/mysql
  app:
    container_name: app_inversify
    build: 
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 3001
    ports:
      - 8080:3001
    volumes:
      - myapp
    depends_on:
      - db
volumes:
  myapp:
